modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="sc"
version="1.0.0"
displayName="Starcraft"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="Admin, MCreator"

[[dependencies.sc]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"



